apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: pavan
  labels:
    app: mysql
    tier: db
    project: pavan
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
      tier: db
      project: pavan
  template:
    metadata:
      labels:
        app: mysql
        tier: db
        project: pavan
    spec:
      containers:
      - name: mysql
        image: pavan095/mysql:v1
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 15
          periodSeconds: 10
---
kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: pavan
spec:
  selector:
    app: mysql
    tier: db
    project: pavan
  ports:
  - name: mysql-port
    protocol: TCP
    port: 3306 # service port
    targetPort: 3306 # container port